### PR TITLE
IPROTO-341 Transcode json array root object

### PR DESCRIPTION
**Pull request by fax4ever**
https://issues.redhat.com/browse/IPROTO-341

### CODE REVIEW

**Comment by tristantarrant** [comment]
I tried running Infinispan's `server/rest` testsuite with a protostream snapshot compiled with this PR and I get the following failure:
```
SearchCountClusteredTest>MultipleCacheManagersTest.createBeforeClass:118->MultipleCacheManagersTest.callCreateCacheManagers:124->MultiNodeRestTest.createCacheManagers:51->MultiNodeRestTest.registerProtobuf:72 » MalformedJson Invalid JSON at [1,2]
```

**Comment by fax4ever** [comment]
> I tried running Infinispan's `server/rest` testsuite with a protostream snapshot compiled with this PR and I get the following failure:
> 
> ```
> SearchCountClusteredTest>MultipleCacheManagersTest.createBeforeClass:118->MultipleCacheManagersTest.callCreateCacheManagers:124->MultiNodeRestTest.createCacheManagers:51->MultiNodeRestTest.registerProtobuf:72 » MalformedJson Invalid JSON at [1,2]
> ```

Thank you @tristantarrant for checking it.
I did the same, basically running the snapshot with the Infinispan CI, but I didn't run the server tests module.
I'm checking it!

**Comment by fax4ever** [comment]
> I tried running Infinispan's `server/rest` testsuite with a protostream snapshot compiled with this PR and I get the following failure:
> 
> ```
> SearchCountClusteredTest>MultipleCacheManagersTest.createBeforeClass:118->MultipleCacheManagersTest.callCreateCacheManagers:124->MultiNodeRestTest.createCacheManagers:51->MultiNodeRestTest.registerProtobuf:72 » MalformedJson Invalid JSON at [1,2]
> ```

Running the server testes I didn't able to reproduce the issue:

``` bash
[ERROR] Failures: 
[ERROR]   FootprintIT.testMemoryFootprint:55 [Heap memory usage] 
Expecting actual:
  28863032L
to be between:
  [23000000L, 25000000L]

[ERROR]   RestMetricsResourceIT.testTimerMetrics:148->findMetric:326 expected: <true> but was: <false>
[INFO] 
[ERROR] Tests run: 2243, Failures: 2, Errors: 0, Skipped: 18
[INFO] 
[INFO] 
[INFO] --- flaky-test-extractor:2.1.1:extract-flaky-tests (default) @ infinispan-server-tests ---
[INFO] FlakyTestExtractorPlugin - starting
[INFO] reportDir: /home/fax/code/infinispan/server/tests/target/surefire-reports
[INFO] failBuild: false
[INFO] FlakyTestExtractorPlugin - finished
[INFO] 
[INFO] --- source:3.3.1:jar-no-fork (attach-sources) @ infinispan-server-tests ---
[INFO] No sources in project. Archive not created.
[INFO] 
[INFO] --- source:3.3.1:test-jar-no-fork (attach-sources) @ infinispan-server-tests ---
[INFO] 
[INFO] --- failsafe:3.2.5:verify (default) @ infinispan-server-tests ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  28:57 min
[INFO] Finished at: 2024-06-26T10:01:27+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:3.2.5:verify (default) on project infinispan-server-tests: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/fax/code/infinispan/server/tests/target/failsafe-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

I remember that we have this `MalformedJson Invalid JSON` in case of concurrent test executions for specific interleaving. I don't know if this could be the case.

**Comment by ryanemerson** [comment]
@fax4ever Do these failures occur every time? If so, I wonder why they're not being picked up by CI.

**Comment by tristantarrant** [comment]
The Infinispan testsuite passed for me. Merging

**Comment by fax4ever** [comment]
Thanks @tristantarrant

**Pull request merged**
