### PR TITLE
IPROTO-239 Use correct generated class

### PR DESCRIPTION
**Pull request by fax4ever**
https://issues.redhat.com/browse/IPROTO-239

### CODE REVIEW

**Comment by pruivo** [comment]
@fax4ever the minimum JDK version is 11. Can't we just use the JDK9+ annotation all the time (and probably update the annotation-api dependency)?

**Comment by gsmet** [comment]
@pruivo we talked about it with Katia but the README seems to indicate you still support a JDK 8 runtime for protostream: `Target runtime platform is Java 8.`. But maybe it hasn't been updated.

**Review by gsmet — APPROVED** [review]
Should fix the issue we have with Quarkus, thanks!

**Comment by pruivo** [comment]
The README isn't updated yet (we forgot). 
We changed the baseline to JDK 11 a while back for Protostream 4.5+
https://github.com/infinispan/protostream/blob/93799230b972131294796d41b5c2d33a79aa0da1/parent/pom.xml#L103-L104

**Comment by gsmet** [comment]
OK, well, in this case, we can just switch to the new annotation. That will simplify things for sure :).

And maybe update the README too.

**Comment by fax4ever** [comment]
Thanks @pruivo and @gsmet for the review.
I pushed the change to remove the annotation-api dependency, we don't need it anymore with JDK 11+.
I put aside the patch to support both JDK 8- and 11+, maybe we can use it if we need to backport the fix to some old ProtoStream version.

**Comment by tristantarrant** [comment]
Merged, thanks

**Comment by fax4ever** [comment]
Thank you!

**Comment by gsmet** [comment]
Thanks!

**Comment by gsmet** [comment]
@fax4ever @tristantarrant @pruivo it would be awesome if you could include this in the next Infinispan 14 dev release!

**Pull request merged**
