### PR TITLE
IPROTO-348 Reproducible builds

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.redhat.com/browse/IPROTO-348

### CODE REVIEW

**Review by ryanemerson — CHANGES_REQUESTED** [review]
I rebased the PR on `main` and Executing the following fails for me:

```
mvn clean install
mvn clean verify artifact:compare
```

```
[INFO] --- artifact:3.5.1:compare (default-cli) @ protostream ---
[WARNING] SCM source tag in buildinfo source.scm.tag=HEAD does not permit rebuilders reproducible source checkout
[INFO] Reference buildinfo file not found: it will be generated from downloaded reference artifacts
[INFO] Reference build java.version: 17 (from MANIFEST.MF Build-Jdk-Spec)
[INFO] Reference build os.name: Unix (from pom.properties newline)
[INFO] Minimal buildinfo generated from downloaded artifacts: /home/remerson/workspace/RedHat/infinispan/protostream/core/target/reference/protostream-5.0.6-SNAPSHOT.buildinfo
[ERROR] sha512 mismatch protostream-5.0.6-SNAPSHOT-sources.jar: investigate with diffoscope core/target/reference/org.infinispan.protostream/protostream-5.0.6-SNAPSHOT-sources.jar core/target/protostream-5.0.6-SNAPSHOT-sources.jar
[ERROR] Reproducible Build output summary: 4 files ok, 1 different
[ERROR] see diff core/target/reference/protostream-5.0.6-SNAPSHOT.buildinfo core/target/protostream-5.0.6-SNAPSHOT.buildinfo
[ERROR] see also https://maven.apache.org/guides/mini/guide-reproducible-builds.html
[INFO] Reproducible Build output comparison saved to /home/remerson/workspace/RedHat/infinispan/protostream/core/target/protostream-5.0.6-SNAPSHOT.buildcompare
```

**Comment by tristantarrant** [comment]
The problem with "sources" artifacts is that they contain generated sources. In our case, Loggers. These have a `@Generated` annotation which includes a timestamp. We should probably fix jboss logging to either remove the timestamp or to use the original source timestamp

**Comment by tristantarrant** [comment]
It seems as if someone has listened to me: https://github.com/jboss-logging/jboss-logging-tools/commit/9e47ba969e7973efab4426abc45ca12ca42fc257

**Comment by tristantarrant** [comment]
While your suggestion sounds good, I'm not really sure how it would work for SNAPSHOT builds

**Pull request merged**
